### ISSUE TITLE
Newest version throws an error when trying to call sitemapper.fetch()

### ISSUE THREAD

**Issue by graylewis** [seantomburke/sitemapper#159]
We're using sitemapper on production and the most recent update broke our pipeline.

This is the code:
```
    const sitemapper = new Sitemapper({
      url: sitemapLocation,
      rejectUnauthorized: false,
    })
    const { sites, errors } = await sitemapper.fetch()
```

We had to rollback to 3.2.12 from 3.2.18 because it started throwing `TypeError: Cannot read properties of undefined (reading 'sites')`

Looking through the releases between 3.2.12-3.2.18, and the lack of a major version increment, I'm assuming this a bug and not a breaking change.

**Comment by graylewis** [comment]
I can confirm that `sitemapLocation` was defined when the function was called

**Comment by peterholc** [comment]
I can confirm I'm having the same issues on 3.2.18, reverting to 3.2.12 fixed it for now.

**Comment by seantomburke** [comment]
Will get this fixed, apologies for the delay!

**Comment by seantomburke** [comment]
@graylewis @peterholc should be fixed now in 3.2.20 with #158. 
Do you have the sitemap URL available to test this? Would like to increase the test coverage to ensure no future regressions.

**Comment by chapmandu** [comment]
I WAS seeing the following error with 3.2.18, it's a different error to that described in the issue, but is also resolved in 3.2.20.

https://www.concretewave.de/sitemap_index.xml

```
Fetching https://www.concretewave.de/sitemap_index.xml
Additional sitemap found during "crawl('https://www.concretewave.de/sitemap_index.xml')"
TypeError: f.sitemapindex.sitemap.map is not a function
    at <anonymous> (/home/adam/myapp/node_modules/sitemapper/src/assets/sitemapper.js:361:12)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/adam/myapp/node_modules/sitemapper/lib/assets/sitemapper.js:1:459)
    at g (/home/adam/myapp/node_modules/sitemapper/lib/assets/sitemapper.js:1:658)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
